# Generated by Django 4.2.1 on 2023-05-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="voiture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marque", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("fuel_type", models.CharField(max_length=100)),
                ("capacity", models.IntegerField()),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("essence", "Essence"),
                            ("Gazoil", "Gazoil"),
                            ("Hybrid", "Hybride"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
