# Generated by Django 4.2.1 on 2023-05-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voiture",
            name="transmission",
            field=models.CharField(
                choices=[("Automatique", "Automatique"), ("Manuelle", "Manuelle")],
                max_length=12,
            ),
        ),
    ]
