# Generated by Django 4.2.1 on 2023-05-26 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="date_depar",
            new_name="date_depart",
        ),
    ]
