# Generated by Django 4.2.1 on 2023-06-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='voiture',
        ),
    ]
