# Generated by Django 4.2.1 on 2023-05-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0002_rename_date_depar_reservation_date_depart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chambre",
            name="disponibilite",
        ),
        migrations.AddField(
            model_name="chambre",
            name="genre",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chambre",
            name="hotel",
            field=models.CharField(max_length=50),
        ),
    ]
