# Generated by Django 4.2.1 on 2023-06-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Booking', '0002_delete_voiture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('depart_time', models.TimeField()),
                ('depart_weekday', models.IntegerField()),
                ('duration', models.DurationField()),
                ('arrival_time', models.TimeField()),
                ('arrival_weekday', models.IntegerField()),
                ('flight_no', models.CharField(max_length=100)),
                ('airline_code', models.CharField(max_length=100)),
                ('airline', models.CharField(max_length=100)),
                ('economy_fare', models.IntegerField(null=True)),
                ('business_fare', models.IntegerField(null=True)),
            ],
        ),
    ]
