# Generated by Django 4.2.1 on 2023-05-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0003_chambre_hotels_utilisateur_reservation_chambre_hotel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="chambre",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="utilisateur",
        ),
        migrations.DeleteModel(
            name="Chambre",
        ),
        migrations.DeleteModel(
            name="Hotels",
        ),
        migrations.DeleteModel(
            name="Reservation",
        ),
        migrations.DeleteModel(
            name="Utilisateur",
        ),
    ]
