# Generated by Django 4.2.1 on 2023-06-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vol',
        ),
    ]
