# Generated by Django 4.2.1 on 2023-05-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0003_remove_chambre_disponibilite_chambre_genre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chambre",
            name="genre",
            field=models.CharField(default="teste", max_length=50),
        ),
    ]
