# Generated by Django 4.2.1 on 2023-05-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0004_alter_chambre_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chambre",
            name="genre",
        ),
        migrations.AddField(
            model_name="chambre",
            name="offre_id",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
