# Generated by Django 4.2.1 on 2023-05-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0004_aeroport_client_compagnie_passager_reserve_ville_vol"),
        ("Booking", "0005_chambre_hotels_utilisateur_reservation_chambre_hotel"),
    ]

    operations = []
