<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-05-24 15:51
=======
# Generated by Django 4.2.1 on 2023-05-25 07:30
>>>>>>> origin/anna

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("Booking", "0006_merge_20230524_1503"),
=======
        ('Booking', '0006_merge_20230525_0730'),
>>>>>>> origin/anna
    ]

    operations = [
        migrations.DeleteModel(
<<<<<<< HEAD
            name="Aeroport",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Compagnie",
        ),
        migrations.DeleteModel(
            name="Passager",
        ),
        migrations.DeleteModel(
            name="reserve",
        ),
        migrations.DeleteModel(
            name="Ville",
        ),
        migrations.DeleteModel(
            name="Vol",
=======
            name='Aeroport',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Compagnie',
        ),
        migrations.DeleteModel(
            name='Passager',
        ),
        migrations.DeleteModel(
            name='reserve',
        ),
        migrations.DeleteModel(
            name='Ville',
        ),
        migrations.DeleteModel(
            name='Vol',
>>>>>>> origin/anna
        ),
    ]
