# Generated by Django 4.2.1 on 2023-05-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0006_merge_20230524_1503"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Aeroport",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Compagnie",
        ),
        migrations.DeleteModel(
            name="Passager",
        ),
        migrations.DeleteModel(
            name="reserve",
        ),
        migrations.DeleteModel(
            name="Ville",
        ),
        migrations.DeleteModel(
            name="Vol",
        ),
    ]
