# Generated by Django 4.2.1 on 2023-06-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_rename_utilisateur_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
