# Generated by Django 4.2.1 on 2023-05-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0007_delete_aeroport_delete_client_delete_compagnie_and_more"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="voiture",
        #     name="year",
        # ),
        # migrations.AddField(
        #     model_name="voiture",
        #     name="image",
        #     field=models.ImageField(blank=True, null=True, upload_to='voiture/'),
        # ),
    ]
