# Generated by Django 4.2.1 on 2023-05-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0008_remove_voiture_year_voiture_image"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="voiture",
        #     name="year",
        # ),
        # migrations.AddField(
        #     model_name="voiture",
        #     name="image",
        #     field=models.CharField(default="", max_length=100),
        # ),
    ]
