# Generated by Django 4.2.1 on 2023-06-12 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Booking", "0010_remove_voiture_year_voiture_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation_voiture",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
