# Generated by Django 4.2.1 on 2023-05-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0010_remove_voiture_year_voiture_image_and_more"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="voiture",
        #     name="year",
        # ),
        migrations.AddField(
            model_name="voiture",
            name="image",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="voiture",
            name="prix_location",
            field=models.IntegerField(default=30000),
        ),
    ]
