# Generated by Django 4.2.1 on 2023-06-12 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Booking", "0011_alter_reservation_voiture_utilisateur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation_voiture",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="utilisateur_id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservation_voiture",
            name="voiture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voiture_id",
                to="Booking.voiture",
            ),
        ),
    ]
